config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls",namespace='homepage')),
    path('auth/',include('account.urls',namespace="account"))
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from os import name
from django.urls import path
from .views import (index,
mainpage,
about,
courses,
lesson,get_involved,
get_uninvolved,
CourseDetailView,
LessonDetailView,
courses_class_filter,
upload_class,
upload_class_category,
upload_courses,
single_lesson,
lesson_upload_ff,
lesson_file_upload,
upload_assingment_file,
student_enrolled_parent)

app_name = "homepage"

urlpatterns = [
    path('', index,name="homepage"),
    path('dashbord',mainpage,name='dashboard'),
    path('about/',about,name="about"),
    path('courses/',courses,name="courses"),
    path('single_lesson/',lesson,name="lesson"),
    path('get_involved/',get_involved,name="get_involved"),
    path('get_uninvolved',get_uninvolved,name="get_uninvolved"),
    path('single_course/<slug>/',CourseDetailView.as_view(),name="single_course"),
    path('single_lesson/<slug>/',single_lesson,name="single_lesson"),
    path('course_class_filter/<slug>/',courses_class_filter,name="course_class_filter"),
    path('upload_class/',upload_class,name="upload_class"),
    path("class_category_upload/",upload_class_category, name="class_category_upload"),
    path('upload_courses/',upload_courses,name="upload_courses"),
    path('upload_lesson/',lesson_upload_ff,name="upload_lessons"),
    path('upload_lesson_file/',lesson_file_upload,name="upload_lessons_file"),
    path('upload_assingment_file/',upload_assingment_file,name="upload_assingment_file"),
    path('student_enrolled_parent/',student_enrolled_parent,name="student_enrolled_parent")

]

homepage/models.py
from django.db import models
import os
import random


# Create your models here.


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "thumbnails/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


class ScrollingIMages(models.Model):
    heading =  models.CharField(max_length=255)
    image = models.ImageField(upload_to = upload_image_path)

    def __str__(self):
        return self.heading


class AboutUs(models.Model):
    heading = models.CharField(max_length=255)
    body =  models.TextField()
    image =  models.ImageField(upload_to=upload_image_path)

    def __str__(self):
        return self.heading

homepage/views.py
from django.core.validators import slug_re
from django.shortcuts import redirect, render
from account.models import User
from django.forms.models import model_to_dict
import uuid

from .models import (ScrollingIMages,
AboutUs)
from account.models import Profile_pic
from courses.models import (ClassCategory, Courses,Enrolment,
Classes,
Lessons,
LessonFiles,
LessonAssignmentFiles
)
from django.views.generic import DetailView,View,ListView

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.http import HttpResponse
from account.models import ChildEmail

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        user_obj =  User.objects.get(id= user_id)
        images =  ScrollingIMages.objects.all()
        about =  AboutUs.objects.all()
        all_courses = Courses.objects.all()
        all_enrolment =  Enrolment.objects.all()
        profile_pic =  Profile_pic.objects.all()

        context ={
            'image' :  images,
            'about' : about,
            'all_courses' :  all_courses,
            'all_enrollmet' : all_enrolment,
            'profile_pic' : profile_pic

        }
        return render(request,'index.html',context)

    else:
        images =  ScrollingIMages.objects.all()
        about =  AboutUs.objects.all()
        all_courses = Courses.objects.all()
        


        context ={
            'image' :  images,
            'about' : about,
            'all_courses' :  all_courses,
            

        }
        return render(request,'index.html',context)


def mainpage(request):
    return render(request,'mainpage.html',{})


def about(request):
    all_teachers =  User.objects.all()
    context = {
        'all_teachers' : all_teachers
    }
    return render(request,'about_us.html',context)


def courses(request):
    if request.user.is_authenticated:
        user =  request.user.id
        # get user with the id
        obj = User.objects.get(id=user)
        dict_user =  model_to_dict(obj)
        user_type = dict_user['type']
        courses =  Courses.objects.all()
        all_users =  User.objects.all()
        all_enrolment =  Enrolment.objects.all()
        all_classes =  Classes.objects.all()

        context = {
            'user_type' : user_type,
            'courses' :  courses,
            'all_users' :  all_users,
            'all_enrollmet' :  all_enrolment,
            'all_classes' :  all_classes
            
        }

        return render(request,'courses.html',context)

    
    else:
        courses =  Courses.objects.all()
        all_classes =  Classes.objects.all()
      
        all_users =  User.objects.all()
        all_enrolment =  Enrolment.objects.all()
        all_classes =  Classes.objects.all()
        context = {
            'courses' :  courses,
            'all_classes' :  all_classes
            
        }

        return render(request,'courses.html',context)

    
        
        


def lesson(request):
    return render(request,'single_lesson.html')


def single_course(request):
    return render(request,'single_course.html')


def get_involved(request):
    if request.method == "POST":
        course_id = request.POST.get("course_id")
        get_course =  Courses.objects.get(id=course_id)
        user_id = request.user.id
        get_user  =  User.objects.get(id=user_id)
        obj,created =  Enrolment.objects.get_or_create(courses_id = get_course,user_id=get_user)
        obj.enrolled =  True
        obj.save()


        return redirect("homepage:courses")



def get_uninvolved(request):
    if request.method == "POST":
        course_id = request.POST.get("course_id")
        get_course =  Courses.objects.get(id=course_id)
        user_id = request.user.id
        get_user  =  User.objects.get(id=user_id)
        obj=  Enrolment.objects.get(courses_id = get_course,user_id=get_user)
        obj.delete()
      


        return redirect("homepage:courses")


class CourseDetailView(DetailView):
    model = Courses
    template_name = "single_course.html"
    def get_context_data(self, **kwargs):
       
        all_enrolment =  Enrolment.objects.all()
        all_lessons =  Lessons.objects.all()

        context = super().get_context_data(**kwargs)
        context['all_enrollement'] = all_enrolment
        context['all_lessons'] =  all_lessons
        
        
        return context






def single_lesson(request,slug):
    singe_l = Lessons.objects.get(id =  slug)
    all_lessons = Lessons.objects.all()
    all_lesson_files = LessonFiles.objects.all()
    assigments =  LessonAssignmentFiles.objects.all()

    context = {
        'object':singe_l,
        'all_lessons' :  all_lessons,
        'lesson_files' :  all_lesson_files,
        'assignemt_files' :  assigments

    }

    return render(request,'single_lesson.html',context)



class LessonDetailView(DetailView):
    model = Lessons
    template_name = "single_lesson.html"

    def get_context_data(self, **kwargs):
        all_lessons = Lessons.objects.all()
        all_lesson_files = LessonFiles.objects.all()
        assigments =  LessonAssignmentFiles.objects.all()
        context = super().get_context_data(**kwargs)
        context['all_lessons'] =  all_lessons
        context['lesson_files'] =  all_lesson_files
        context['assignemt_files'] =  assigments


def courses_class_filter(request, slug):
    if request.user.is_authenticated:
        user =  request.user.id
        # get user with the id
        obj = User.objects.get(id=user)
        dict_user =  model_to_dict(obj)
        user_type = dict_user['type']
        courses =  Courses.objects.all()
        all_users =  User.objects.all()
        all_enrolment =  Enrolment.objects.all()
        print(slug)
        filtered_classes =  Classes.objects.get(id= slug)
        all_classes =  Classes.objects.all()

        context = {
            'user_type' : user_type,
            'courses' :  courses,
            'all_users' :  all_users,
            'all_enrollmet' :  all_enrolment,
            'all_classes' :  all_classes,
            'filtered_classes' :  filtered_classes
            
        }

        return render(request,'classes_filter.html',context)

    
    else:
        courses =  Courses.objects.all()
        all_classes =  Classes.objects.all()
        filtered_classes =  Classes.objects.get(slug= slug)

        context = {
            
            'courses' :  courses,
            'all_classes' :  all_classes,
            'filtered_classes ' :  filtered_classes
            
        }

        return render(request,'classes_filter.html',context)


def upload_class(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            class_name =  request.POST.get('class_name')
            user =  request.user.id
            # get user with the id
            obju = User.objects.get(id=user)
            slug =  str(uuid.uuid4().hex) + str(class_name).strip().replace(" ","_")
            obj,created = Classes.objects.get_or_create(user_id = obju,slug = slug)
            obj.class_name = class_name
            obj.active =  True
            obj.save()
            request.session['class_id'] = obj.id
            return redirect("homepage:class_category_upload")
    return render(request,'upload_class.html')



def upload_class_category(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            class_name =  request.POST.get('class_title')
            class_uploaded =  request.session['class_id']
            get_class =  Classes.objects.get(id= int(class_uploaded))
            slug =  str(uuid.uuid4().hex) + str(class_name).strip().replace(" ","_")
            obj,created = ClassCategory.objects.get_or_create(class_id = get_class,slug=slug)
            obj.class_title = class_name
            obj.save()
            request.session['class_category_id'] = obj.id
            return redirect("homepage:upload_courses")
    return render(request,'upload_class_category.html')


def upload_courses(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            class_name_title = request.POST.get('course_title')
            class_short_description = request.POST.get('course_short_description')
            class_long_description = request.POST.get('course_long_description')
            class_language = request.POST.get('course_language')
            class_thumbnails = request.FILES['course_thumbnail']
            class_video_url = request.POST.get('video_url')
            user_id =  request.user.id
            user_obj =  User.objects.get(id=  user_id)
            class_category =  request.session['class_category_id']
            slug =  str(uuid.uuid4().hex) + str(class_name_title).strip().replace(" ","_")
            class_category_obj = ClassCategory.objects.get(id =  class_category)
            couses =  Courses.objects.create(
                title = class_name_title,
                teacher_id = user_obj,
                course_category = class_category_obj,
                short_description = class_short_description,
                description = class_long_description,
                language = class_language,
                thumbnail = class_thumbnails,
                video_url = class_video_url,
                is_published = True,
                slug = slug
            )
            request.session['class_courses_id'] = couses.id
            return redirect("homepage:upload_lessons")
    
    return render(request,'upload_courses.html')


def lesson_upload_ff(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            lesson_title =  request.POST.get('lesson_title')

homepage/templates/home_sections/our_expertie.html
{% load static %}

 <!--Our expertise section one start -->
        <div class="ed_transprentbg ed_toppadder90">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="ed_heading_top">
                            <h3>Choose how you want to learn</h3>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="ed_populer_areas_slider">
                            <div class="owl-carousel owl-theme">
                                <div class="item">
                                    <div class="ed_item_img">
                                        <img src="{% static 'assets/images/kidscamp/slider/crs1.jpg' %}" alt="item1" class="img-responsive">
                                    </div>
                                    <div class="ed_item_description">
                                        <h4>Vocational Counselling</h4>
                                        <p>Vocational counselling is a career focused on helping people who need to find a job. Pretty obvious, obvious right?</p>
                                        <a href="javascript:void(0);" class="ed_getinvolved">get involved <i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="ed_item_img">
                                        <img src="{% static 'assets/images/kidscamp/slider/crs2.jpg' %}" alt="item2" class="img-responsive">
                                    </div>
                                    <div class="ed_item_description">
                                        <h4>Elementary School</h4>
                                        <p>Vocational counselling is a career focused on helping people who need to find a job. Pretty obvious, obvious right?</p>
                                        <a href="javascript:void(0);" class="ed_getinvolved">get involved <i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="ed_item_img">
                                        <img src="{% static 'assets/images/kidscamp/slider/crs3.jpg' %}" alt="item3" class="img-responsive">
                                    </div>
                                    <div class="ed_item_description">
                                        <h4>Student Guidance</h4>
                                        <p>Vocational counselling is a career focused on helping people who need to find a job. Pretty obvious, obvious right?</p>
                                        <a href="javascript:void(0);" class="ed_getinvolved">get involved <i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="ed_item_img">
                                        <img src="{% static 'assets/images/kidscamp/slider/crs4.jpg' %}" alt="item4" class="img-responsive">
                                    </div>
                                    <div class="ed_item_description">
                                        <h4>Psychology Tests</h4>
                                        <p>Vocational counselling is a career focused on helping people who need to find a job. Pretty obvious, obvious right?</p>
                                        <a href="javascript:void(0);" class="ed_getinvolved">get involved <i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="ed_item_img">
                                        <img src="{% static 'assets/images/kidscamp/slider/crs5.jpg' %}" alt="item1" class="img-responsive">
                                    </div>
                                    <div class="ed_item_description">
                                        <h4>individual attention</h4>
                                        <p>Vocational counselling is a career focused on helping people who need to find a job. Pretty obvious, obvious right?</p>
                                        <a href="javascript:void(0);" class="ed_getinvolved">get involved <i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="ed_item_img">
                                        <img src="{% static 'assets/images/kidscamp/slider/crs6.jpg' %}" alt="item2" class="img-responsive">
                                    </div>
                                    <div class="ed_item_description">
                                        <h4>Peer Recognition</h4>
                                        <p>Vocational counselling is a career focused on helping people who need to find a job. Pretty obvious, obvious right?</p>
                                        <a href="javascript:void(0);" class="ed_getinvolved">get involved <i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.container -->
        </div>
        <!--Our expertise section one end -->

homepage/templates/home_sections/recommended_courses.html
{% load static %}

 <!-- Most recomended Courses Section four start -->
        <div class="ed_transprentbg ed_toppadder80 ed_bottompadder80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="ed_heading_top ed_bottompadder80">
                            <h3>Learner recommended courses</h3>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="ed_mostrecomeded_course_slider ed_mostrecomededcourseslider">
                            <div id="owl-demo3" class="owl-carousel owl-theme">
                               
                               {% if all_courses %}
                               {% for all in all_courses  %}
                                <div class="item">
                                    <div class="ed_item_img">
                                        <img src="{{all.thumbnail.url}}" alt="item1" class="img-responsive">
                                    </div>
                                    <div class="ed_item_description ed_most_recomended_data">
                                        <h4><a href="{{all.get_absolute_url}}">{{all.title}}</a></h4>
                                        <div class="row">
                                    
                                        </div>
                                        <div class="course_detail">
                                            <div class="course_faculty">
                                                <img src="{% static 'assets/images/kidscamp/content/team_1.jpg'  %}" alt=""> <a href="javascript:void(0);">{{all.teacher_id.username}}</a>
                                            </div>
                                        </div>
                                        <p>{{all.short_description}}</p>
                                        {% if request.user.is_authenticated %}


                                        {% if all_enrollmet %}
                                        {% for mkli in all_enrollmet %}
                                        {% if mkli.courses_id.id == all.id %}
                                            {% if  mkli.enrolled %}
                                                    <form method="POST" action="{% url 'homepage:get_uninvolved' %}">
                                            
                                                        {% csrf_token %}

                                                        <input name="course_id" type="hidden" value="{{all.id}}" >
                                                        
                                                        <button type="submit" class="btn btn-danger">Remove Enrollment</button>
                                                    </form>


                                            {% else %}
                                                    <form method="POST" action="{% url 'homepage:get_involved' %}">
                                  
                                                        {% csrf_token %}

                                                        <input name="course_id" type="hidden" value="{{all.id}}" >
                                                        
                                                        <button type="submit" class="btn btn-success">Enroll Now</button>
                                                    </form>
                                        
                                        
                                        
                                        
                                        
                                                {% endif %}



                                        {% else %}
                                        <form method="POST" action="{% url 'homepage:get_involved' %}">
                                    
                                                    {% csrf_token %}

                                                    <input name="course_id" type="hidden" value="{{all.id}}" >
                                                    
                                                    <button type="submit" class="btn btn-success">Enroll Now</button>
                                                </form>



                                        
                                        
                                        {% endif %}

                                        {% endfor %}

                                            {% else %}

                                            

                                                <form method="POST" action="{% url 'homepage:get_involved' %}">
                                              
                                                    {% csrf_token %}

                                                    <input name="course_id" type="hidden" value="{{all.id}}" >
                                                    
                                                    <button type="submit" class="btn btn-success">Enroll Now</button>
                                                </form>
                                        
                                        {% endif %}


                                       
                                        {% endif %}
                                    </div>
                                </div>

                                {% endfor %}

                                {% endif %}
                              
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.container -->
        </div>
        <!--Most recomended Courses Section four end -->
       

homepage/templates/home_sections/sliding.html
   {% load static %}
   
   <div class="ed_slider_form_section">
            <!--Slider start-->
            <section class="ed_mainslider">
                <article class="content">
                    <div class="rev_slider_wrapper">
                        <!-- START REVOLUTION SLIDER 5.0 auto mode -->
                        <div id="rev_slider_4_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="classicslider1" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
                            <div id="rev_slider" class="rev_slider " data-version="5.0">
                                <ul>

                                {% if image %}

                                {% for p in image  %}
                                    <!-- SLIDE  -->
                                    <li data-transition="boxfade">

                                        <!-- MAIN IMAGE -->
                                        <img src="{{p.image.url}}" alt="">
                                        <div class="ed_course_single_image_overlay"></div>

                                        <!-- LAYER NR. 1 -->
                                        <div class="tp-caption NotGeneric-Title   tp-resizeme rs-parallaxlevel-0" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['220','2205','195','135']" data-width="none" data-height="none"
                                            data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-50px;skX:100px;opacity:0;s:2000;e:Power4.easeInOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-start="1510"
                                            data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="z-index: 5; white-space: nowrap; font-size: 60px; color:#fff; font-family: 'Merienda One', cursive;">{{p.heading}}
                                        </div>
                                        <div class="tp-caption NotGeneric-Title   tp-resizeme rs-parallaxlevel-0" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['300','235','210','200']" data-width="none" data-height="none"
                                            data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-50px;skX:100px;opacity:0;s:2000;e:Power4.easeInOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-start="1810"
                                            data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="z-index: 5; white-space: nowrap; font-size: 60px; color:#fff; font-family: 'Merienda One', cursive;">
                                        </div>

                                        <!-- LAYER NR. 2 -->
                                        <div class="tp-caption NotGeneric-CallToAction ed_btn ed_green tp-resizeme rs-parallaxlevel-0" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['430','306','776','651']"
                                            data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                                            data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap; ">
                                            {% if request.user.is_authenticated %}

                                            Welcome

                                            {% else %} 

                                            Sign In


                                            {% endif %}
                                        </div>

                                    </li>
                                 
                                    <!-- SLIDE  -->

                                {% endfor %}

                                {% endif %}

                                </ul>
                            </div>
                            <!-- END REVOLUTION SLIDER -->
                        </div>
                        <!-- END  -->
                    </div>
                    <!-- END REVOLUTION SLIDER WRAPPER -->
                </article>
            </section>
            <!--Slider end-->
            <!--Slider form start-->
           
            <!--Slider form end-->
        </div>
      

homepage/templates/home_sections/video_section.html
{% load static %}

<!--video_section Section three start -->
        <div class="ed_parallax_section">
            <div class="ed_img_overlay"></div>
            <div class="container">
                <div class="row">
                {% if about %}
                {% for i in about  %}
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="ed_video_section">
                            <div class="embed-responsive embed-responsive-16by9">
                                <div class="ed_video">
                               
                                    <img src="{{i.image.url}}" style="cursor:pointer" alt="1" />
                                    <div class="ed_img_overlay">
                                        <a href="javascript:void(0);"><i class="fa fa-play-circle" aria-hidden="true"></i></a>
                                    </div>
                                </div>
                                <iframe id="educo_video" class="embed-responsive-item" src="https://www.youtube.com/embed/8mb-0qbq984" allowfullscreen></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="ed_video_section_discription">
                            <h4>{{i.heading}}</h4>
                            <p>{{i.body}}</p>
                            <span><a href="{% url 'homepage:about' %}" class="btn ed_btn ed_orange">see more</a></span>
                        </div>
                    </div>
                {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
        <!--video_section Section three end -->
       