account/urls.py
from django.urls import path
from .views import (index,signup,logout_user,profile_image,activate_account,
parent_child_email)


app_name = "account"

urlpatterns = [
    path('', index,name="sign_in"),
    path('signup/', signup,name="sign_up"),
    path('logout',logout_user,name="logout"),
    path('profile_image/',profile_image,name="upload_image"),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_account, name='activate'),
    path('parent_child_email/',parent_child_email,name="parent_child_email")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls",namespace='homepage')),
    path('auth/',include('account.urls',namespace="account"))
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from courses.models import upload_image_path
import os
import random

# Create your models here.

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "thumbnails/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )



class User(AbstractUser):
    email = models.EmailField(verbose_name='email',max_length=255,unique=True)
    phone = models.CharField(null=True,max_length=255)
    type = models.CharField(null=True,max_length=255)
    
    
    REQUIRED_FIELDS = ['username','phone','first_name','last_name','type']
    USERNAME_FIELD = 'email'

    def get_username(self):
        return self.email



class ChildEmail(models.Model):
    parent_id =  models.ForeignKey(User,on_delete=models.CASCADE)
    child_email =  models.EmailField()

    def __str__(self):
        return self.child_email


class Profile_pic(models.Model):
    user_id =  models.ForeignKey(User,on_delete=models.CASCADE)
    image =  models.ImageField(upload_to =  upload_image_path)
    image_filled =  models.BooleanField(default=False)

    def __str__(self):
        return str(self.user_id)

account/forms.py
from django import forms
from .models import Profile_pic

class SignINForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"email" , "placeholder":"Email", "id":"username",
             "required":""

        }
    ))

    password = forms.CharField(
        widget=forms.PasswordInput(
           attrs={ "type":"password" ,"placeholder":"Password", "id":"password",
            "required":""}
        )
    )

    


class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"text" , "placeholder":"Username", "id":"username",
             "required":""

        }
    ))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"text" , "placeholder":"First Name", "id":"username",
             "required":""

        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"emailaddress", "type":"text" , "placeholder":"Last Name", "id":"username",
             "required":""

        }
    ))

    phone = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"phone", "type":"text" , "placeholder":"Phone Number", "id":"phone",
             "required":""

        }
    ))

    type = forms.CharField(widget=forms.TextInput(
        attrs={
            "name":"type", "type":"text" , "placeholder":"Type ...", "id":"type",
             "required":""

        }
    ))

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            "name":"emailaddress", "type":"email" , "placeholder":"Username", "id":"email",
             "required":""

        }
    ))

    password = forms.CharField(
        widget=forms.PasswordInput(
           attrs={ "type":"password" ,"placeholder":"Password", "id":"password",
            "required":""}
        )
    )


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = Profile_pic
        fields = ['image']

account/views.py
from django.shortcuts import redirect, render
from .forms import SignINForm,SignUpForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User
from account.models import User
from django.contrib.auth import logout
from .forms import UploadImageForm
from .models import User
from .models import Profile_pic

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token
from django.core.mail import EmailMessage
from django.http import HttpResponse
from .models import ChildEmail

# Create your views here.
def logout_user(request):
    logout(request)
    return redirect("/")

def index(request):

    login_form = SignINForm(request.POST,None)

    
    context = {
        'login' : login_form
    }
    
    if login_form.is_valid:
        username = request.POST.get("username")
        password = request.POST.get("password")
        print(username,password)
        user = authenticate(request,username = username, password = password )
        print("jjja",user)
        if user is not None:
        
            login(request,user)
            return redirect("homepage:homepage")
        else:
            pass
    return render(request,'signin.html',context)


def signup(request):
    sign_up = SignUpForm(request.POST,None)

    context =  { 
        "form" :sign_up
    }
    if request.method =='POST':
        if sign_up.is_valid:
            username = request.POST.get("username")
            first_name = request.POST.get("first_name")
            last_name =  request.POST.get("last_name")
            type = request.POST.get("type")
            phone =  request.POST.get("phone")
            email = request.POST.get('email')
            password = request.POST.get("password")
            user = authenticate(request,username = email, password = password )
            if user is not None:
                print("user exists")
                return redirect("account:sign_in")
            else:
                
                user = User.objects.create_user(username = username , email = email , password = password)
                user.last_name = last_name
                user.first_name = first_name
                user.type =  type
                user.phone = phone
                user.is_active =  False
                user.save()
                current_site = get_current_site(request)
                email_subject = 'Activate Your Account'
                message = render_to_string('activate_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
                })
                to_email = email
                email = EmailMessage(email_subject, message, to=[to_email])
                email.send()
                return HttpResponse('We have sent you an email, please confirm your email address to complete registration')

    return render(request,'signup.html',context)


def profile_image(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
  
        if form.is_valid():
            image =  request.FILES["image"]
            if request.user.is_authenticated:
                user =  request.user.id
                user_obj =  User.objects.get(id=  user)
                obj,created =  Profile_pic.objects.get_or_create(user_id = user_obj)
                obj.image = image
                obj.save()

                return redirect("/")


            else:
                return redirect("accounts:sign_in")
    else:
        form = UploadImageForm()
    return render(request, 'upload_image.html', {'form' : form})


def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request,user)
        current_site = get_current_site(request)
        email_subject = 'Successfull Registration'
        message = render_to_string('successfull_regestration.html', {
        'user': user,
        'domain': current_site.domain
        })
        to_email = user.email
        email = EmailMessage(email_subject, message, to=[to_email])
        email.send()

        if user.type == "Parent":
            print("Parent user",user.username)
            return render(request,'parent_child_email.html')



        return HttpResponse('Your account has been activate successfully')
        
    else:
        return HttpResponse('Activation link is invalid!')




@login_required(login_url="account:sign_in")
def parent_child_email(request):
    if request.method == "POST":
        email =  request.POST.get("email")
        user = User.objects.get(email =  email)
        if user.type == "Student":
            user_now  =  request.user.id
            user_obj = User.objects.get(id = user_now)
            ms = ChildEmail.objects.create(
                parent_id = user_obj,
                child_email = user.email

            )

            return redirect("/")
        return render(request,'parent_child_email.html')

    return render(request,'parent_child_email.html')

    

    

account/templates/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}
{% endautoescape %}

account/templates/parent_child_email.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elearning</title>
    <link rel="stylesheet" href="{% static './css/signin_signup/style.css' %}">
</head>
<body>
    
    <div class="container">
        <div class="header">
            <h2>Child Email</h2>
        </div>
        <form method="POST" action="{% url 'account:parent_child_email' %}" id="form" class="form">
            {% csrf_token %}
            
            <div class="form-control">
                <label for="username">Email</label>
                <input name="email"  type="text"  placeholder="Enter childs email"  id="type"
                required="">
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
            <button>Submit</button>
            
        </form>
    </div>
    
    
    
    
</body>
</html>

account/templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elearning</title>
    <link rel="stylesheet" href="{% static './css/signin_signup/style.css'  %}">
</head>
<body>
    
    <div class="container">
        <div class="header">
            <h2>Login</h2>
        </div>
        <form method="POST" action="{% url 'account:sign_in' %}" id="form" class="form">
            {% csrf_token %}
            
            <div class="form-control">
                <label for="username">Email</label>
                {{login.username}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
            <div class="form-control">
                <label for="username">Password</label>
                {{login.password}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
            
            <button>Submit</button>
            <a  href="{% url 'account:sign_up' %}">Sign Up</a>
        </form>
    </div>
    
    
    
    
</body>
</html>

account/templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elearning</title>
    <link rel="stylesheet" href="{% static './css/signin_signup/style.css' %}">
</head>
<body>
    
    <div class="container">
        <div class="header">
            <h2>Sign Up</h2>
        </div>
        <form method="POST" action="{% url 'account:sign_up' %}" id="form" class="form">
            {% csrf_token %}
            
            <div class="form-control">
                <label for="username">Username</label>
                {{form.username}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>

            <div class="form-control">
                <label for="username">First Name</label>
                {{form.first_name}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>

            <div class="form-control">
                <label for="username">Last Name</label>
                {{form.last_name}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>


            <div class="form-control">
                <label for="username">Phone Number</label>
                {{form.phone}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>



            <div class="form-control">
                <label for="username">Email</label>
                {{form.email}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>

            <div class="form-control">
                <label for="username">Type</label>
               
                <select name="type" style="padding:10px;width:100%;border-color: #7971ea;" id="cars">
                    <option value="Student">Student</option>
                    <option value="Teacher">Teacher</option>
                    <option value="Parent">Parent</option>
                    
                    
                </select>
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>

            <div class="form-control">
                <label for="username">Password</label>
                {{form.password}}
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
           
            <button>Submit</button>
            <a  href="{% url 'account:sign_in' %}">Sign In</a>
        </form>
    </div>
    
    
    
    
</body>
</html>

account/templates/successfull_regestration.html
{% autoescape off %}
Hi {{ user.username }},
Thank you for registering with us, follow this link to go to homepage
http://{{ domain }}
{% endautoescape %}

account/templates/upload_image.html
{% extends 'base.html' %}

{% block content %}

<h1> Upload profile image </h1>


<form method = "post" enctype="multipart/form-data" action="{% url 'account:upload_image' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
</form>


{% endblock %}